#
# Copyright 2017-present, DoorTwoDoor, Inc.
# All rights reserved.
#
# This source code is licensed under the Apache-style license found in the
# LICENSE file in the root directory of this source tree.
#

# The version of the API in the given runtime environment that is used by
# your app.
api_version: go1

# A list of URL patterns and descriptions of how they should be handled.
handlers: 
- url: /.*
  script: _go_app

# The name of the App Engine runtime environment used by this application.
runtime: go
