#
# Copyright 2017-present, DoorTwoDoor, Inc.
# All rights reserved.
#
# This source code is licensed under the Apache-style license found in the
# LICENSE file in the root directory of this source tree.
#

# application is mandatory
application: doortwodoor-7e677

# version is mandatory
version: 1-0

# runtime is mandatory
runtime: go

# api_version is mandatory
api_version: go1

# handlers is mandatory
handlers:
- url: /.*
  script: _go_app
